name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

env: 
  CARGO_TERM_COLOR: always
  rust_min: '1.81'

jobs:
  stable_test:
    name: Stable Rust Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose --all-features
      - run: cargo test --verbose --all-features
  
  minrust_test:
    name: Min Rust Version Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.rust_min }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_min }}
      - run: cargo build --verbose --all-features
      - run: cargo test --verbose --all-features

